# Generated by Django 6.0.4 on 2026-04-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lessoncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
